### PR TITLE
chore(dependencies): update pmuir/project1 from 0.2.11 to 2.1.12

### PR DESCRIPTION
**Pull request by pmuir**
Update pmuir/project1 from 0.2.11 to 2.1.12.

Command run was `jx step create pr chart --repo https://github.com/pmuir/project2 --name athens-proxy --version 2.1.12`

### CODE REVIEW

**Comment by pmuir** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **pmuir**

If they are not already assigned, you can assign the PR to them by writing `/assign @pmuir` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=pmuir%2Fproject2).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/pmuir/project2/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by muirp-owner** [comment]
:star: PR built and available in a preview environment **pmuir-project2-pr-2** [here](http://project2.jx-pmuir-project2-pr-2.35.241.202.58.nip.io)

**Comment by pmuir** [comment]
@pmuir: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
serverless-jenkins | 30a5a7b480047d2ca0e5caa45c0064ccd31b2256 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by muirp-owner** [comment]
:star: PR built and available in a preview environment **pmuir-project2-pr-2**

**Comment by pmuir** [comment]
@pmuir: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
serverless-jenkins | f8e421fe948c1225ff70da8b435d89f17910ffae | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by pmuir** [comment]
@pmuir: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
serverless-jenkins | f8e421fe948c1225ff70da8b435d89f17910ffae | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Pull request closed without merging**
